### ISSUE TITLE
Client never switch state from Connecting to Connected

### ISSUE THREAD

**Issue by antoshib** [antlafarge/QtWebsocket#30]
From client side using QWsSocket I can't establish connection with websocket server (php), it switched from "HostLookup" to "Connecting" and than to "Unconnected". ClientJS can successfully connect and receive messages from it server. 
As I see log-file on server, connection handshake passed fine:
```
2015-07-19T11:22:23Z|Host: 172.16.0.40
2015-07-19T11:22:23Z|Upgrade: websocket
2015-07-19T11:22:23Z|Connection: Upgrade
2015-07-19T11:22:23Z|Sec-WebSocket-Key: ZTEKM0hLqshseJ+2ewMXRg==
2015-07-19T11:22:23Z|Sec-WebSocket-Version: 13
2015-07-19T11:22:23Z|HACCEPTED
```
PHP server handshake answer to client:
```
HTTP/1.1 101 Web Socket Protocol Handshake
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept:mqepEY7qWTYYHdDRsGU+M4yKCR0=
```
What can be the reason?

**Comment by antlafarge** [comment]
Hi, thank you for the report. But the project is not more maintained because Qt integrates a websocket native support.  
You can look here: http://doc.qt.io/qt-5/qtwebsockets-index.html  

If you want to use this version. You have to know I didn't test QtWebsocket with the php websocket server. Maybe some debug is necessary in the client side (maybe here: QWsHandshake::isValid).
Anyway, even if the project is deprecated. I can apply a pull request.

**Comment by antoshib** [comment]
Hi! I already found the bug, it was in ````Sec-WebSocket-Accept:mqepEY7qWTYYHdDRsGU+M4yKCR0=```` string because of missing space after colon. QtWebSockets is just fine, but I should to build application under Qt 4.7 and distribute it to ancient Angstrom Linux. Thanks of a lot!

**Comment by antlafarge** [comment]
Okay great !
